### ISSUE TITLE
Exception when -d is not specified (default to current directory?)

### ISSUE THREAD

**Issue by mchubby** [dingtoffee/StickyPraser#2]
StickyPraser: Parsing the sqlite file ....
StickyParser: Saving the csv file
Traceback (most recent call last):
  File "C:\EXTRACT\StickyParser-master\stickyparser.py", line 265, in <module>
    plum(args.p.name)
  File "C:\EXTRACT\StickyParser-master\stickyparser.py", line 56, in plum
    db_df.to_csv(args.d+ 'stickynoteresultplum-'+ now + '.csv', index=False)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

You might also want to use the logging module, it's ultra quick to get started and prevents some typos ;)
https://rollbar.com/blog/logging-in-python/

**Comment by iamhunggy** [comment]
Will look into it. It makes sense. will update its default directory.

**Comment by iamhunggy** [comment]
Updated to default to current directory.
