### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by GenesisAdam** [dingtoffee/StickyPraser#3]
File "C:\StickyParser\stickyparser.py", line 260
    args.d = args.d +　'\\'
                     ^
SyntaxError: invalid non-printable character U+3000

**Comment by iamhunggy** [comment]
Latest version was updated to resolve the syntax error.

**Comment by GenesisAdam** [comment]
Still getting error as shown below:

Traceback (most recent call last):
  File "C:\StickyParser\stickyparser.py", line 3, in <module>
    import olefile
ModuleNotFoundError: No module named 'olefile'

**Comment by iamhunggy** [comment]
Seems like you have not installed the relevant python packages before running. Could you please run pip install to get all the libraries first? “pip install olefile” on your command line. 

If you have not installed pandas, you should do the same.

**Comment by GenesisAdam** [comment]
How do I install pandas?

Thank you.

**Comment by GenesisAdam** [comment]
> Seems like you have not installed the relevant python packages before running. Could you please run pip install to get all the libraries first? “pip install olefile” on your command line. If you have not installed pandas, you should do the same.

I have installed pandas. It runs successfully but no ouput was produced.
I run it with the following:
stickyparser.py -d C:\StickyNotesbk
The C:\StickyNotesbk folder contains plum.sqlite-shm and plum.sqlite-wal but no sqllite.
I am doing something wrong.
I am just tring to recover my notes.
