### ISSUE TITLE
Full Text of notes not in CSV

### ISSUE THREAD

**Issue by stark4n6** [dingtoffee/StickyPraser#4]
Just from brief testing stream 3 in each note may not contain the full text as some appear truncated. I do see the full text in stream 1 after ASCII "\fs22" although I'm not sure how to properly carve it out. This is for Windows 7. Was just wondering if you could take a look, thanks.

**Comment by dingtoffee** [comment]
Let me look at it.

**Comment by iamhunggy** [comment]
Could you give me a sample to replicate the issue? I was creating sample sticky note on windows 7 but it looks like all the text I put is available in stream 3 of each sticky note.

**Comment by stark4n6** [comment]
Do you have a good email I can share with?

**Comment by dingtoffee** [comment]
Please share this to andytaylor0102 at outlook.com

**Comment by stark4n6** [comment]
Email sent

**Comment by iamhunggy** [comment]
It looks like the text is truncated after reaching 50 characters (space included). Thanks for spotting that out. I have rewritten the function to use Stream 0 instead.

**Comment by stark4n6** [comment]
Thanks, will give it a try again shortly

**Comment by stark4n6** [comment]
Worked like a charm, thanks so much!
